[workspace]
authors = ["Ali Khan <alik@robarts.ca>"]
channels = ["conda-forge", "bioconda", "khanlab"]
name = "cfmm2bids"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.13"
snakebids = ">=0.14.0,<0.15"
heudiconv = ">=1.3.4,<2"
dcm4che-tools = ">=5.33.1,<6"

[pypi-dependencies]
cfmm2tar = { path = "/localscratch/cfmm2tar" , editable=true}
