[workspace]
authors = ["Ali Khan <alik@robarts.ca>"]
channels = ["conda-forge", "bioconda", "khanlab"]
name = "cfmm2bids"
platforms = ["linux-64"]
version = "0.1.0"


[dependencies]
python = ">=3.11,<3.13"
#snakebids = ">=0.14.0,<0.15"
dcm4che-tools = ">=5.33.1,<6"
dcm2niix = ">=1.0.20250506,<2"
snakemake = ">=9.13.3,<10"
highdicom = ">=0.26.1,<0.27"
nibabel = ">=5.3.2,<6"
matplotlib = ">=3.10.7,<4"
snakemake-executor-plugin-slurm = ">=1.4.0,<2"


[pypi-dependencies]
cfmm2tar = { git = "https://github.com/khanlab/cfmm2tar", rev = "master" }
heudiconv = { git = "https://github.com/khanlab/heudiconv", rev = "master"}
bids-validator-deno = ">=2.2.0,<3"
ruff = ">=0.8.0,<0.9"
snakefmt = ">=0.10.0,<0.11"
pre-commit = ">=4.0.0,<5"
pytest = ">=8.0.0,<9"

